FROM ubuntu:latest

RUN apt update && apt install -y \
  wget \
  curl \
  zip \
  unzip \
  git \
  git-lfs \
  cmake \
  make \
  python3 \
  python3-pip \
  python3-venv \
  clang-19 \
  clang-format-19 \
  clang-tidy-19
